services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    networks:
      - microservices-network
    environment:
      - SPRING_PROFILES_ACTIVE=git
    depends_on:
      - eureka-server



  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    networks:
      - microservices-network
    depends_on:
      - eureka-server
      - config-server

networks:
  microservices-network:
    driver: bridge
