server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ExeCarrizo33/config-repository
          clone-on-start: true
          default-label: master
        bootstrap: true
